// Created with resguy v8 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/fullmoonbk.tga
gfx/env/fullmoondn.tga
gfx/env/fullmoonft.tga
gfx/env/fullmoonlf.tga
gfx/env/fullmoonrt.tga
gfx/env/fullmoonup.tga
models/afrikakorps/misc/gascan.mdl
models/aomdc/barnacle.mdl
models/aomdc/bullchicken.mdl
models/bushes/bigbush.mdl
models/bushes/bush.mdl
models/corpse_female1.mdl
models/hunger/hungerzork.mdl
models/hunger/p_hunger357.mdl
models/hunger/svenhands/p_hunger9mmar.mdl
models/hunger/svenhands/p_hunger9mmhandgun.mdl
models/hunger/svenhands/p_hungercrossbow.mdl
models/hunger/svenhands/p_hungersatchel.mdl
models/hunger/svenhands/p_hungersatchel_radio.mdl
models/hunger/svenhands/p_hungershotgun.mdl
models/hunger/svenhands/p_m40a1.mdl
models/hunger/svenhands/v_hunger357.mdl
models/hunger/svenhands/v_hunger9mmar.mdl
models/hunger/svenhands/v_hunger9mmhandgun.mdl
models/hunger/svenhands/v_hungercrossbow.mdl
models/hunger/svenhands/v_hungersatchel.mdl
models/hunger/svenhands/v_hungersatchel_radio.mdl
models/hunger/svenhands/v_hungershotgun.mdl
models/hunger/svenhands/v_m40a1.mdl
models/hunger/svenhands/v_tnt.mdl
models/hunger/svenhands/w_hunger9mmar.mdl
models/hunger/svenhands/w_hunger9mmhandgun.mdl
models/hunger/svenhands/w_hungercrossbow.mdl
models/hunger/svenhands/w_hungersatchel.mdl
models/hunger/svenhands/w_hungershotgun.mdl
models/hunger/svenhands/w_m40a1.mdl
models/hunger/w_hunger357.mdl
models/keenhalloween/grass.mdl
models/keenhalloween/p_firehose.mdl
models/keenhalloween/p_medkit.mdl
models/keenhalloween/pumpkin2.mdl
models/keenhalloween/pumpkinsnark.mdl
models/keenhalloween/v_firehose.mdl
models/keenhalloween/v_medkit.mdl
models/keenhalloween/v_pumpkin.mdl
models/keenhalloween/w_firehose.mdl
models/keenhalloween/w_pmedkit.mdl
models/opfor/p_knife.mdl
models/opfor/svenhands/v_knife.mdl
models/opfor/w_knife.mdl
models/oxyhalloween/p_rustybloodm16.mdl
models/oxyhalloween/v_bgrap_fixed.mdl
models/oxyhalloween/v_bgraptip.mdl
models/oxyhalloween/v_rustybloodm16.mdl
models/oxyhalloween/w_rustybloodm16.mdl
models/sc_activist/houndeye.mdl
models/sc_activist/houndeyet.mdl
models/sc_activist/icky.mdl
models/sc_activist/ickyt.mdl
models/sectore/cryogrunt.mdl
models/turr/eye.mdl
models/turr/p_keyboard.mdl
models/turr/v_keyboard.mdl
models/turr/w_keyboard.mdl
sound/aomlowercase/barnacle/bcl_alert2.wav
sound/aomlowercase/barnacle/bcl_bite3.wav
sound/aomlowercase/barnacle/bcl_die1.wav
sound/aomlowercase/barnacle/bcl_die3.wav
sound/aomlowercase/barnacle/bcl_tongue1.wav
sound/aomlowercase/bullchicken/bc_acid1.wav
sound/aomlowercase/bullchicken/bc_acid2.wav
sound/aomlowercase/bullchicken/bc_attack1.wav
sound/aomlowercase/bullchicken/bc_attack2.wav
sound/aomlowercase/bullchicken/bc_attack3.wav
sound/aomlowercase/bullchicken/bc_attackgrowl.wav
sound/aomlowercase/bullchicken/bc_attackgrowl2.wav
sound/aomlowercase/bullchicken/bc_attackgrowl3.wav
sound/aomlowercase/bullchicken/bc_bite1.wav
sound/aomlowercase/bullchicken/bc_bite2.wav
sound/aomlowercase/bullchicken/bc_bite3.wav
sound/aomlowercase/bullchicken/bc_die1.wav
sound/aomlowercase/bullchicken/bc_die2.wav
sound/aomlowercase/bullchicken/bc_die3.wav
sound/aomlowercase/bullchicken/bc_idle1.wav
sound/aomlowercase/bullchicken/bc_idle2.wav
sound/aomlowercase/bullchicken/bc_idle3.wav
sound/aomlowercase/bullchicken/bc_idle4.wav
sound/aomlowercase/bullchicken/bc_idle5.wav
sound/aomlowercase/bullchicken/bc_pain1.wav
sound/aomlowercase/bullchicken/bc_pain2.wav
sound/aomlowercase/bullchicken/bc_pain3.wav
sound/aomlowercase/bullchicken/bc_pain4.wav
sound/aomlowercase/bullchicken/bc_spithit1.wav
sound/aomlowercase/bullchicken/bc_spithit2.wav
sound/aomlowercase/bullchicken/bc_spithit3.wav
sound/aomlowercase/houndeye/he_alert1.wav
sound/aomlowercase/houndeye/he_alert2.wav
sound/aomlowercase/houndeye/he_alert3.wav
sound/aomlowercase/houndeye/he_attack1.wav
sound/aomlowercase/houndeye/he_attack2.wav
sound/aomlowercase/houndeye/he_attack3.wav
sound/aomlowercase/houndeye/he_blast1.wav
sound/aomlowercase/houndeye/he_blast2.wav
sound/aomlowercase/houndeye/he_blast3.wav
sound/aomlowercase/houndeye/he_die1.wav
sound/aomlowercase/houndeye/he_die2.wav
sound/aomlowercase/houndeye/he_die3.wav
sound/aomlowercase/houndeye/he_hunt1.wav
sound/aomlowercase/houndeye/he_hunt2.wav
sound/aomlowercase/houndeye/he_hunt3.wav
sound/aomlowercase/houndeye/he_hunt4.wav
sound/aomlowercase/houndeye/he_idle1.wav
sound/aomlowercase/houndeye/he_pain1.wav
sound/aomlowercase/houndeye/he_pain2.wav
sound/aomlowercase/houndeye/he_pain3.wav
sound/aomlowercase/houndeye/he_pain4.wav
sound/aomlowercase/houndeye/he_pain5.wav
sound/aomlowercase/zombie2/claw_miss1.wav
sound/aomlowercase/zombie2/claw_miss2.wav
sound/aomlowercase/zombie2/claw_strike1.wav
sound/aomlowercase/zombie2/claw_strike2.wav
sound/aomlowercase/zombie2/claw_strike3.wav
sound/aomlowercase/zombie2/zo_alert10.wav
sound/aomlowercase/zombie2/zo_alert20.wav
sound/aomlowercase/zombie2/zo_alert30.wav
sound/aomlowercase/zombie2/zo_attack1.wav
sound/aomlowercase/zombie2/zo_attack2.wav
sound/aomlowercase/zombie2/zo_idle1.wav
sound/aomlowercase/zombie2/zo_idle2.wav
sound/aomlowercase/zombie2/zo_idle3.wav
sound/aomlowercase/zombie2/zo_idle4.wav
sound/aomlowercase/zombie2/zo_pain1.wav
sound/aomlowercase/zombie2/zo_pain2.wav
sound/bluecell/eyeballcry.wav
sound/bluecell/picardnotenough.wav
sound/keen/locksmith.wav
sound/keenhalloween/3bells.wav
sound/keenhalloween/break.wav
sound/keenhalloween/break2.wav
sound/keenhalloween/ckdeadgun.wav
sound/keenhalloween/creak1.wav
sound/keenhalloween/creak2.wav
sound/keenhalloween/creak3.wav
sound/keenhalloween/dialogs/kh1/keenradio1.ogg
sound/keenhalloween/hks1.wav
sound/keenhalloween/howl3.wav
sound/keenhalloween/jp_intro01.wav
sound/keenhalloween/jp_intro02.wav
sound/keenhalloween/jp_intro03.wav
sound/keenhalloween/owl.wav
sound/keenhalloween/pipegroan.wav
sound/keenhalloween/pl_gun3.wav
sound/keenhalloween/statix.wav
sound/keenhalloween/thehouse.wav
sound/keenhalloween/wallbreak.wav
sound/keenhalloween/waterblast.wav
sound/keenhalloween/watercannonoff.wav
sound/keenhalloween/watercannonon.wav
sound/keenhalloween/welldrain.wav
sound/keenrpg/getitem.wav
sound/omg/picard.wav
sound/secretroom/ritalin.wav
sound/sectore/spaceambient.wav
sound/tur/blt2.wav
sound/tur/boss.wav
sound/tur/cloud.wav
sound/tur/coin.wav
sound/tur/dipper2.wav
sound/tur/goldcoin.wav
sound/tur/hongkong3.wav
sound/tur/metalslug.wav
sound/tur/slidje3.wav
sound/tur/turkey.wav
sound/tur/viraldrone.wav
sound/tur/x2.wav
sound/weapons/1911meu/MagIn.wav
sound/weapons/1911meu/MagOut.wav
sound/weapons/1911meu/SlidePull.wav
sound/weapons/1911meu/Sliderelease.wav
sprites/fog6.spr
sprites/keenhalloween/picardcoin.spr