// Created with resguy v8 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/fullmoonbk.tga
gfx/env/fullmoondn.tga
gfx/env/fullmoonft.tga
gfx/env/fullmoonlf.tga
gfx/env/fullmoonrt.tga
gfx/env/fullmoonup.tga
models/afrikakorps/misc/gascan.mdl
models/aomdc/barnacle.mdl
models/aomdc/bullchicken.mdl
models/cryocell/cryoslave.mdl
models/cryocell/cryoslave01.mdl
models/cryocell/cryoslave02.mdl
models/hunger/hungerzork.mdl
models/hunger/p_hunger357.mdl
models/hunger/svenhands/p_hunger9mmar.mdl
models/hunger/svenhands/p_hunger9mmhandgun.mdl
models/hunger/svenhands/p_hungercrossbow.mdl
models/hunger/svenhands/p_hungersatchel.mdl
models/hunger/svenhands/p_hungersatchel_radio.mdl
models/hunger/svenhands/p_hungershotgun.mdl
models/hunger/svenhands/p_m40a1.mdl
models/hunger/svenhands/v_hunger357.mdl
models/hunger/svenhands/v_hunger9mmar.mdl
models/hunger/svenhands/v_hunger9mmhandgun.mdl
models/hunger/svenhands/v_hungercrossbow.mdl
models/hunger/svenhands/v_hungersatchel.mdl
models/hunger/svenhands/v_hungersatchel_radio.mdl
models/hunger/svenhands/v_hungershotgun.mdl
models/hunger/svenhands/v_m40a1.mdl
models/hunger/svenhands/v_tnt.mdl
models/hunger/svenhands/w_hunger9mmar.mdl
models/hunger/svenhands/w_hunger9mmhandgun.mdl
models/hunger/svenhands/w_hungercrossbow.mdl
models/hunger/svenhands/w_hungersatchel.mdl
models/hunger/svenhands/w_hungershotgun.mdl
models/hunger/svenhands/w_m40a1.mdl
models/hunger/w_hunger357.mdl
models/keenhalloween/p_firehose.mdl
models/keenhalloween/p_medkit.mdl
models/keenhalloween/pumpkin2.mdl
models/keenhalloween/pumpkinsnark.mdl
models/keenhalloween/v_firehose.mdl
models/keenhalloween/v_medkit.mdl
models/keenhalloween/v_pumpkin.mdl
models/keenhalloween/w_firehose.mdl
models/keenhalloween/w_pmedkit.mdl
models/opfor/p_knife.mdl
models/opfor/svenhands/v_knife.mdl
models/opfor/w_knife.mdl
models/oxyhalloween/p_rustybloodm16.mdl
models/oxyhalloween/v_bgrap_fixed.mdl
models/oxyhalloween/v_bgraptip.mdl
models/oxyhalloween/v_rustybloodm16.mdl
models/oxyhalloween/w_rustybloodm16.mdl
models/psychic_agog/bunker_labspook.mdl
models/psychic_agog/bunker_scientist.mdl
models/psychic_agog/bunker_scientist01.mdl
models/psychic_agog/bunker_scientist02.mdl
models/psychic_agog/bunker_scientist03.mdl
models/psychic_agog/bunker_scientist04.mdl
models/psychic_agog/whitecorpse.mdl
models/richard_boderman/plant.mdl
models/sc_activist/houndeye.mdl
models/sc_activist/houndeyet.mdl
models/sc_activist/icky.mdl
models/sc_activist/ickyt.mdl
models/sectore/darkdrone3.mdl
models/turr/p_keyboard.mdl
models/turr/v_keyboard.mdl
models/turr/w_keyboard.mdl
sound/aomlowercase/barnacle/bcl_alert2.wav
sound/aomlowercase/barnacle/bcl_bite3.wav
sound/aomlowercase/barnacle/bcl_die1.wav
sound/aomlowercase/barnacle/bcl_die3.wav
sound/aomlowercase/barnacle/bcl_tongue1.wav
sound/aomlowercase/bullchicken/bc_acid1.wav
sound/aomlowercase/bullchicken/bc_acid2.wav
sound/aomlowercase/bullchicken/bc_attack1.wav
sound/aomlowercase/bullchicken/bc_attack2.wav
sound/aomlowercase/bullchicken/bc_attack3.wav
sound/aomlowercase/bullchicken/bc_attackgrowl.wav
sound/aomlowercase/bullchicken/bc_attackgrowl2.wav
sound/aomlowercase/bullchicken/bc_attackgrowl3.wav
sound/aomlowercase/bullchicken/bc_bite1.wav
sound/aomlowercase/bullchicken/bc_bite2.wav
sound/aomlowercase/bullchicken/bc_bite3.wav
sound/aomlowercase/bullchicken/bc_die1.wav
sound/aomlowercase/bullchicken/bc_die2.wav
sound/aomlowercase/bullchicken/bc_die3.wav
sound/aomlowercase/bullchicken/bc_idle1.wav
sound/aomlowercase/bullchicken/bc_idle2.wav
sound/aomlowercase/bullchicken/bc_idle3.wav
sound/aomlowercase/bullchicken/bc_idle4.wav
sound/aomlowercase/bullchicken/bc_idle5.wav
sound/aomlowercase/bullchicken/bc_pain1.wav
sound/aomlowercase/bullchicken/bc_pain2.wav
sound/aomlowercase/bullchicken/bc_pain3.wav
sound/aomlowercase/bullchicken/bc_pain4.wav
sound/aomlowercase/bullchicken/bc_spithit1.wav
sound/aomlowercase/bullchicken/bc_spithit2.wav
sound/aomlowercase/bullchicken/bc_spithit3.wav
sound/aomlowercase/houndeye/he_alert1.wav
sound/aomlowercase/houndeye/he_alert2.wav
sound/aomlowercase/houndeye/he_alert3.wav
sound/aomlowercase/houndeye/he_attack1.wav
sound/aomlowercase/houndeye/he_attack2.wav
sound/aomlowercase/houndeye/he_attack3.wav
sound/aomlowercase/houndeye/he_blast1.wav
sound/aomlowercase/houndeye/he_blast2.wav
sound/aomlowercase/houndeye/he_blast3.wav
sound/aomlowercase/houndeye/he_die1.wav
sound/aomlowercase/houndeye/he_die2.wav
sound/aomlowercase/houndeye/he_die3.wav
sound/aomlowercase/houndeye/he_hunt1.wav
sound/aomlowercase/houndeye/he_hunt2.wav
sound/aomlowercase/houndeye/he_hunt3.wav
sound/aomlowercase/houndeye/he_hunt4.wav
sound/aomlowercase/houndeye/he_idle1.wav
sound/aomlowercase/houndeye/he_pain1.wav
sound/aomlowercase/houndeye/he_pain2.wav
sound/aomlowercase/houndeye/he_pain3.wav
sound/aomlowercase/houndeye/he_pain4.wav
sound/aomlowercase/houndeye/he_pain5.wav
sound/classic/items/9mmclip1.wav
sound/keen/breakout_remix.mod
sound/keen/endlvlmusicfade.mp3
sound/keen/locksmith.wav
sound/keen/mine_sequence.wav
sound/keen/prepare.wav
sound/keen/qbertjaxhardcore.mp3
sound/keen/reinforcements.wav
sound/keen/rescuesci2.wav
sound/keen/rescuesci3.mp3
sound/keenhalloween/dialogs/kh4/2ndwavemsg.ogg
sound/keenhalloween/dialogs/kh4/2ndwavesuccess.ogg
sound/keenhalloween/dialogs/kh4/canistertext.ogg
sound/keenhalloween/dialogs/kh4/canistertext2.ogg
sound/keenhalloween/dialogs/kh4/canistertext3.ogg
sound/keenhalloween/dialogs/kh4/rescuesci1set.ogg
sound/keenhalloween/fart1.wav
sound/keenhalloween/hks1.wav
sound/keenhalloween/hongkong4.wav
sound/keenhalloween/pl_gun3.wav
sound/keenhalloween/rikeralert.wav
sound/keenhalloween/running.wav
sound/keenhalloween/smooth.wav
sound/keenhalloween/waterblast.wav
sound/keenhalloween/watercannonoff.wav
sound/keenhalloween/watercannonon.wav
sound/keenrpg/getitem.wav
sound/keenweather/lightning.wav
sound/necroscasm/claw_miss1.wav
sound/necroscasm/claw_miss2.wav
sound/necroscasm/claw_strike1.wav
sound/necroscasm/claw_strike2.wav
sound/necroscasm/claw_strike3.wav
sound/necroscasm/zo_alert10.wav
sound/necroscasm/zo_alert20.wav
sound/necroscasm/zo_alert30.wav
sound/necroscasm/zo_attack1.wav
sound/necroscasm/zo_attack2.wav
sound/necroscasm/zo_idle1.wav
sound/necroscasm/zo_idle2.wav
sound/necroscasm/zo_idle3.wav
sound/necroscasm/zo_idle4.wav
sound/necroscasm/zo_pain1.wav
sound/necroscasm/zo_pain2.wav
sound/sectore/hks1.wav
sound/sectore/hks2.wav
sound/sectore/hks3.wav
sound/sectore/pit_drone_alert1.wav
sound/sectore/pit_drone_alert2.wav
sound/sectore/pit_drone_alert3.wav
sound/sectore/pit_drone_attack_spike1.wav
sound/sectore/pit_drone_attack_spike2.wav
sound/sectore/pit_drone_communicate1.wav
sound/sectore/pit_drone_communicate2.wav
sound/sectore/pit_drone_communicate3.wav
sound/sectore/pit_drone_communicate4.wav
sound/sectore/pit_drone_die1.wav
sound/sectore/pit_drone_die2.wav
sound/sectore/pit_drone_die3.wav
sound/sectore/pit_drone_eat.wav
sound/sectore/pit_drone_hunt1.wav
sound/sectore/pit_drone_hunt2.wav
sound/sectore/pit_drone_hunt3.wav
sound/sectore/pit_drone_idle1.wav
sound/sectore/pit_drone_idle2.wav
sound/sectore/pit_drone_idle3.wav
sound/sectore/pit_drone_melee_attack1.wav
sound/sectore/pit_drone_melee_attack2.wav
sound/sectore/pit_drone_pain1.wav
sound/sectore/pit_drone_pain2.wav
sound/sectore/pit_drone_pain3.wav
sound/sectore/pit_drone_pain4.wav
sound/sectore/pl_gun1.wav
sound/sectore/pl_gun2.wav
sound/sectore/pl_gun3.wav
sound/tur/coin.wav
sound/weapons/1911meu/MagIn.wav
sound/weapons/1911meu/MagOut.wav
sound/weapons/1911meu/SlidePull.wav
sound/weapons/1911meu/Sliderelease.wav
sprites/keenhalloween/picardcoin.spr