// Created with resguy v8 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/dwellbk.tga
gfx/env/dwelldn.tga
gfx/env/dwellft.tga
gfx/env/dwelllf.tga
gfx/env/dwellrt.tga
gfx/env/dwellup.tga
models/afrikakorps/misc/gascan.mdl
models/aomdc/barnacle.mdl
models/aomdc/bullchicken.mdl
models/hunger/hungerzork.mdl
models/hunger/p_hunger357.mdl
models/hunger/svenhands/p_hunger9mmar.mdl
models/hunger/svenhands/p_hunger9mmhandgun.mdl
models/hunger/svenhands/p_hungercrossbow.mdl
models/hunger/svenhands/p_hungersatchel.mdl
models/hunger/svenhands/p_hungersatchel_radio.mdl
models/hunger/svenhands/p_hungershotgun.mdl
models/hunger/svenhands/p_m40a1.mdl
models/hunger/svenhands/v_hunger357.mdl
models/hunger/svenhands/v_hunger9mmar.mdl
models/hunger/svenhands/v_hunger9mmhandgun.mdl
models/hunger/svenhands/v_hungercrossbow.mdl
models/hunger/svenhands/v_hungersatchel.mdl
models/hunger/svenhands/v_hungersatchel_radio.mdl
models/hunger/svenhands/v_hungershotgun.mdl
models/hunger/svenhands/v_m40a1.mdl
models/hunger/svenhands/v_tnt.mdl
models/hunger/svenhands/w_hunger9mmar.mdl
models/hunger/svenhands/w_hunger9mmhandgun.mdl
models/hunger/svenhands/w_hungercrossbow.mdl
models/hunger/svenhands/w_hungersatchel.mdl
models/hunger/svenhands/w_hungershotgun.mdl
models/hunger/svenhands/w_m40a1.mdl
models/hunger/w_hunger357.mdl
models/keenhalloween/mr_zombie2.mdl
models/keenhalloween/mr_zombie3.mdl
models/keenhalloween/p_firehose.mdl
models/keenhalloween/p_medkit.mdl
models/keenhalloween/pumpkin2.mdl
models/keenhalloween/pumpkinsnark.mdl
models/keenhalloween/skeleshark.mdl
models/keenhalloween/v_firehose.mdl
models/keenhalloween/v_medkit.mdl
models/keenhalloween/v_pumpkin.mdl
models/keenhalloween/w_firehose.mdl
models/keenhalloween/w_pmedkit.mdl
models/opfor/p_knife.mdl
models/opfor/svenhands/v_knife.mdl
models/opfor/w_knife.mdl
models/oxyhalloween/p_rustybloodm16.mdl
models/oxyhalloween/v_bgrap_fixed.mdl
models/oxyhalloween/v_bgraptip.mdl
models/oxyhalloween/v_rustybloodm16.mdl
models/oxyhalloween/w_rustybloodm16.mdl
models/rngstuff/rc_bottle1.mdl
models/rngstuff/rc_bottle2.mdl
models/sc_activist/houndeye.mdl
models/sc_activist/houndeyet.mdl
models/sc_activist/icky.mdl
models/sc_activist/ickyt.mdl
models/turr/p_keyboard.mdl
models/turr/v_keyboard.mdl
models/turr/w_keyboard.mdl
sound/aomlowercase/barnacle/bcl_alert2.wav
sound/aomlowercase/barnacle/bcl_bite3.wav
sound/aomlowercase/barnacle/bcl_die1.wav
sound/aomlowercase/barnacle/bcl_die3.wav
sound/aomlowercase/barnacle/bcl_tongue1.wav
sound/aomlowercase/bullchicken/bc_acid1.wav
sound/aomlowercase/bullchicken/bc_acid2.wav
sound/aomlowercase/bullchicken/bc_attack1.wav
sound/aomlowercase/bullchicken/bc_attack2.wav
sound/aomlowercase/bullchicken/bc_attack3.wav
sound/aomlowercase/bullchicken/bc_attackgrowl.wav
sound/aomlowercase/bullchicken/bc_attackgrowl2.wav
sound/aomlowercase/bullchicken/bc_attackgrowl3.wav
sound/aomlowercase/bullchicken/bc_bite1.wav
sound/aomlowercase/bullchicken/bc_bite2.wav
sound/aomlowercase/bullchicken/bc_bite3.wav
sound/aomlowercase/bullchicken/bc_die1.wav
sound/aomlowercase/bullchicken/bc_die2.wav
sound/aomlowercase/bullchicken/bc_die3.wav
sound/aomlowercase/bullchicken/bc_idle1.wav
sound/aomlowercase/bullchicken/bc_idle2.wav
sound/aomlowercase/bullchicken/bc_idle3.wav
sound/aomlowercase/bullchicken/bc_idle4.wav
sound/aomlowercase/bullchicken/bc_idle5.wav
sound/aomlowercase/bullchicken/bc_pain1.wav
sound/aomlowercase/bullchicken/bc_pain2.wav
sound/aomlowercase/bullchicken/bc_pain3.wav
sound/aomlowercase/bullchicken/bc_pain4.wav
sound/aomlowercase/bullchicken/bc_spithit1.wav
sound/aomlowercase/bullchicken/bc_spithit2.wav
sound/aomlowercase/bullchicken/bc_spithit3.wav
sound/aomlowercase/houndeye/he_alert1.wav
sound/aomlowercase/houndeye/he_alert2.wav
sound/aomlowercase/houndeye/he_alert3.wav
sound/aomlowercase/houndeye/he_attack1.wav
sound/aomlowercase/houndeye/he_attack2.wav
sound/aomlowercase/houndeye/he_attack3.wav
sound/aomlowercase/houndeye/he_blast1.wav
sound/aomlowercase/houndeye/he_blast2.wav
sound/aomlowercase/houndeye/he_blast3.wav
sound/aomlowercase/houndeye/he_die1.wav
sound/aomlowercase/houndeye/he_die2.wav
sound/aomlowercase/houndeye/he_die3.wav
sound/aomlowercase/houndeye/he_hunt1.wav
sound/aomlowercase/houndeye/he_hunt2.wav
sound/aomlowercase/houndeye/he_hunt3.wav
sound/aomlowercase/houndeye/he_hunt4.wav
sound/aomlowercase/houndeye/he_idle1.wav
sound/aomlowercase/houndeye/he_pain1.wav
sound/aomlowercase/houndeye/he_pain2.wav
sound/aomlowercase/houndeye/he_pain3.wav
sound/aomlowercase/houndeye/he_pain4.wav
sound/aomlowercase/houndeye/he_pain5.wav
sound/classic/items/9mmclip1.wav
sound/hlhotdog/spooky_wind.wav
sound/keen/breakout_remix.mod
sound/keen/locksmith.wav
sound/keenhalloween/campfirelargeloop.wav
sound/keenhalloween/dialogs/kh5/maz_hlair_trigtxt1a.ogg
sound/keenhalloween/dialogs/kh5/maz_texte1.ogg
sound/keenhalloween/dialogs/kh5/maz_texte2.ogg
sound/keenhalloween/dialogs/kh5/mazur_horseloltxt1.ogg
sound/keenhalloween/farm_house1.mp3
sound/keenhalloween/farm_weird.wav
sound/keenhalloween/hks1.wav
sound/keenhalloween/horsemen/horseman_attack_01.wav
sound/keenhalloween/horsemen/horseman_attack_05.wav
sound/keenhalloween/horsemen/horseman_bodydefeat_01.wav
sound/keenhalloween/horsemen/horseman_bomb_01.wav
sound/keenhalloween/horsemen/horseman_failing_02.wav
sound/keenhalloween/horsemen/horseman_laugh_01.wav
sound/keenhalloween/horsemen/horseman_out_01.wav
sound/keenhalloween/horsemen/horseman_special_01.wav
sound/keenhalloween/horsemen/horseman_wound_03.wav
sound/keenhalloween/horsemen/horseman_wound_04.wav
sound/keenhalloween/horsemen/horseman_wound_07.wav
sound/keenhalloween/horsemen/horseman_wound_08.wav
sound/keenhalloween/horsemen/horseman_woundcrit_05.wav
sound/keenhalloween/lavastreamloop.wav
sound/keenhalloween/lemonbats.wav
sound/keenhalloween/lemonmusic1.wav
sound/keenhalloween/mazur_firestart.wav
sound/keenhalloween/mz_port_suckin1.wav
sound/keenhalloween/owl.wav
sound/keenhalloween/pl_gun3.wav
sound/keenhalloween/scourge_horn.wav
sound/keenhalloween/waterblast.wav
sound/keenhalloween/watercannonoff.wav
sound/keenhalloween/watercannonon.wav
sound/tur/coin.wav
sound/weapons/1911meu/MagIn.wav
sound/weapons/1911meu/MagOut.wav
sound/weapons/1911meu/SlidePull.wav
sound/weapons/1911meu/Sliderelease.wav
sprites/flames.spr
sprites/keenhalloween/lemonbatsies.spr
sprites/keenhalloween/lemonghost.spr
sprites/wosc/flames.spr