// Created with resguy v8 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/ionusbk.tga
gfx/env/ionusdn.tga
gfx/env/ionusft.tga
gfx/env/ionuslf.tga
gfx/env/ionusrt.tga
gfx/env/ionusup.tga
models/afrikakorps/misc/gascan.mdl
models/aomdc/barnacle.mdl
models/aomdc/bullchicken.mdl
models/bushes/bigbush.mdl
models/corpse_female1.mdl
models/gordonsci/friendlygonome2.mdl
models/gordonsci/friendlyhound.mdl
models/hunger/hungerzork.mdl
models/hunger/p_hunger357.mdl
models/hunger/svenhands/p_hunger9mmar.mdl
models/hunger/svenhands/p_hunger9mmhandgun.mdl
models/hunger/svenhands/p_hungercrossbow.mdl
models/hunger/svenhands/p_hungersatchel.mdl
models/hunger/svenhands/p_hungersatchel_radio.mdl
models/hunger/svenhands/p_hungershotgun.mdl
models/hunger/svenhands/p_m40a1.mdl
models/hunger/svenhands/v_hunger357.mdl
models/hunger/svenhands/v_hunger9mmar.mdl
models/hunger/svenhands/v_hunger9mmhandgun.mdl
models/hunger/svenhands/v_hungercrossbow.mdl
models/hunger/svenhands/v_hungersatchel.mdl
models/hunger/svenhands/v_hungersatchel_radio.mdl
models/hunger/svenhands/v_hungershotgun.mdl
models/hunger/svenhands/v_m40a1.mdl
models/hunger/svenhands/v_tnt.mdl
models/hunger/svenhands/w_hunger9mmar.mdl
models/hunger/svenhands/w_hunger9mmhandgun.mdl
models/hunger/svenhands/w_hungercrossbow.mdl
models/hunger/svenhands/w_hungersatchel.mdl
models/hunger/svenhands/w_hungershotgun.mdl
models/hunger/svenhands/w_m40a1.mdl
models/hunger/w_hunger357.mdl
models/keen/obcgrunt.mdl
models/keenhalloween/g1l/fixed/big_mom.mdl
models/keenhalloween/p_firehose.mdl
models/keenhalloween/p_medkit.mdl
models/keenhalloween/pumpkin2.mdl
models/keenhalloween/pumpkinsnark.mdl
models/keenhalloween/v_firehose.mdl
models/keenhalloween/v_medkit.mdl
models/keenhalloween/v_pumpkin.mdl
models/keenhalloween/w_firehose.mdl
models/keenhalloween/w_pmedkit.mdl
models/kh6/cryokeen.mdl
models/opfor/p_knife.mdl
models/opfor/svenhands/v_knife.mdl
models/opfor/w_knife.mdl
models/oxyhalloween/p_rustybloodm16.mdl
models/oxyhalloween/v_bgrap_fixed.mdl
models/oxyhalloween/v_bgraptip.mdl
models/oxyhalloween/v_rustybloodm16.mdl
models/oxyhalloween/w_rustybloodm16.mdl
models/rngstuff/labspook.mdl
models/sc_activist/houndeye.mdl
models/sc_activist/houndeyet.mdl
models/sc_activist/icky.mdl
models/sc_activist/ickyt.mdl
models/sectore/cryogrunt.mdl
models/sectore/freeman.mdl
models/sectore/gordon.mdl
models/turr/p_keyboard.mdl
models/turr/v_keyboard.mdl
models/turr/w_keyboard.mdl
sound/aomlowercase/barnacle/bcl_alert2.wav
sound/aomlowercase/barnacle/bcl_bite3.wav
sound/aomlowercase/barnacle/bcl_die1.wav
sound/aomlowercase/barnacle/bcl_die3.wav
sound/aomlowercase/barnacle/bcl_tongue1.wav
sound/aomlowercase/bullchicken/bc_acid1.wav
sound/aomlowercase/bullchicken/bc_acid2.wav
sound/aomlowercase/bullchicken/bc_attack1.wav
sound/aomlowercase/bullchicken/bc_attack2.wav
sound/aomlowercase/bullchicken/bc_attack3.wav
sound/aomlowercase/bullchicken/bc_attackgrowl.wav
sound/aomlowercase/bullchicken/bc_attackgrowl2.wav
sound/aomlowercase/bullchicken/bc_attackgrowl3.wav
sound/aomlowercase/bullchicken/bc_bite1.wav
sound/aomlowercase/bullchicken/bc_bite2.wav
sound/aomlowercase/bullchicken/bc_bite3.wav
sound/aomlowercase/bullchicken/bc_die1.wav
sound/aomlowercase/bullchicken/bc_die2.wav
sound/aomlowercase/bullchicken/bc_die3.wav
sound/aomlowercase/bullchicken/bc_idle1.wav
sound/aomlowercase/bullchicken/bc_idle2.wav
sound/aomlowercase/bullchicken/bc_idle3.wav
sound/aomlowercase/bullchicken/bc_idle4.wav
sound/aomlowercase/bullchicken/bc_idle5.wav
sound/aomlowercase/bullchicken/bc_pain1.wav
sound/aomlowercase/bullchicken/bc_pain2.wav
sound/aomlowercase/bullchicken/bc_pain3.wav
sound/aomlowercase/bullchicken/bc_pain4.wav
sound/aomlowercase/bullchicken/bc_spithit1.wav
sound/aomlowercase/bullchicken/bc_spithit2.wav
sound/aomlowercase/bullchicken/bc_spithit3.wav
sound/aomlowercase/houndeye/he_alert1.wav
sound/aomlowercase/houndeye/he_alert2.wav
sound/aomlowercase/houndeye/he_alert3.wav
sound/aomlowercase/houndeye/he_attack1.wav
sound/aomlowercase/houndeye/he_attack2.wav
sound/aomlowercase/houndeye/he_attack3.wav
sound/aomlowercase/houndeye/he_blast1.wav
sound/aomlowercase/houndeye/he_blast2.wav
sound/aomlowercase/houndeye/he_blast3.wav
sound/aomlowercase/houndeye/he_die1.wav
sound/aomlowercase/houndeye/he_die2.wav
sound/aomlowercase/houndeye/he_die3.wav
sound/aomlowercase/houndeye/he_hunt1.wav
sound/aomlowercase/houndeye/he_hunt2.wav
sound/aomlowercase/houndeye/he_hunt3.wav
sound/aomlowercase/houndeye/he_hunt4.wav
sound/aomlowercase/houndeye/he_idle1.wav
sound/aomlowercase/houndeye/he_pain1.wav
sound/aomlowercase/houndeye/he_pain2.wav
sound/aomlowercase/houndeye/he_pain3.wav
sound/aomlowercase/houndeye/he_pain4.wav
sound/aomlowercase/houndeye/he_pain5.wav
sound/escape_series/escape2_escape_route.mp3
sound/keen/locksmith.wav
sound/keen/rescuesci3.mp3
sound/keen/shaboochaa.wav
sound/keen/shd_dt_cheap1.mp3
sound/keen/shd_dt_cheap8.mp3
sound/keen/uhah.wav
sound/keenhalloween/dialogs/kh6/attack.ogg
sound/keenhalloween/dialogs/kh6/miniboss.ogg
sound/keenhalloween/dialogs/kh6/nihtalkblah.ogg
sound/keenhalloween/dialogs/kh6/shieldgo.ogg
sound/keenhalloween/dialogs/kh6/trannys.ogg
sound/keenhalloween/earthquake1.wav
sound/keenhalloween/hks1.wav
sound/keenhalloween/lava.wav
sound/keenhalloween/pl_gun3.wav
sound/keenhalloween/rikeralert.wav
sound/keenhalloween/smooth.wav
sound/keenhalloween/waterblast.wav
sound/keenhalloween/watercannonoff.wav
sound/keenhalloween/watercannonon.wav
sound/keenweather/lightning.wav
sound/kh6/all12coinsget.wav
sound/kh6/bennyhill_loud.mp3
sound/kh6/fuzz.wav
sound/kh6/greatwork.wav
sound/kh6/helloplayers.wav
sound/kh6/ysoserious.wav
sound/necroscasm/claw_miss1.wav
sound/necroscasm/claw_miss2.wav
sound/necroscasm/claw_strike1.wav
sound/necroscasm/claw_strike2.wav
sound/necroscasm/claw_strike3.wav
sound/necroscasm/zo_alert10.wav
sound/necroscasm/zo_alert20.wav
sound/necroscasm/zo_alert30.wav
sound/necroscasm/zo_attack1.wav
sound/necroscasm/zo_attack2.wav
sound/necroscasm/zo_idle1.wav
sound/necroscasm/zo_idle2.wav
sound/necroscasm/zo_idle3.wav
sound/necroscasm/zo_idle4.wav
sound/necroscasm/zo_pain1.wav
sound/necroscasm/zo_pain2.wav
sound/nihsounds/robotsrobots.wav
sound/sectore/278161_Gravitational_Pull_2_.mp3
sound/sectore/341422_Iysis__HighTreson_.mp3
sound/sectore/doompickup.wav
sound/shell/cheer.wav
sound/tur/coin.wav
sound/tur/hongkong3.wav
sound/weapons/1911meu/MagIn.wav
sound/weapons/1911meu/MagOut.wav
sound/weapons/1911meu/SlidePull.wav
sound/weapons/1911meu/Sliderelease.wav
sprites/fog2.spr
sprites/keenhalloween/picardcoin.spr