// Created with resguy v8 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/dawnbk.tga
gfx/env/dawndn.tga
gfx/env/dawnft.tga
gfx/env/dawnlf.tga
gfx/env/dawnrt.tga
gfx/env/dawnup.tga
models/JustZombies/monster/controller_drone.mdl
models/afrikakorps/misc/gascan.mdl
models/aomdc/barnacle.mdl
models/aomdc/bullchicken.mdl
models/hunger/hungerzork.mdl
models/hunger/p_hunger357.mdl
models/hunger/svenhands/p_hunger9mmar.mdl
models/hunger/svenhands/p_hunger9mmhandgun.mdl
models/hunger/svenhands/p_hungercrossbow.mdl
models/hunger/svenhands/p_hungersatchel.mdl
models/hunger/svenhands/p_hungersatchel_radio.mdl
models/hunger/svenhands/p_hungershotgun.mdl
models/hunger/svenhands/p_m40a1.mdl
models/hunger/svenhands/v_hunger357.mdl
models/hunger/svenhands/v_hunger9mmar.mdl
models/hunger/svenhands/v_hunger9mmhandgun.mdl
models/hunger/svenhands/v_hungercrossbow.mdl
models/hunger/svenhands/v_hungersatchel.mdl
models/hunger/svenhands/v_hungersatchel_radio.mdl
models/hunger/svenhands/v_hungershotgun.mdl
models/hunger/svenhands/v_m40a1.mdl
models/hunger/svenhands/v_tnt.mdl
models/hunger/svenhands/w_hunger9mmar.mdl
models/hunger/svenhands/w_hunger9mmhandgun.mdl
models/hunger/svenhands/w_hungercrossbow.mdl
models/hunger/svenhands/w_hungersatchel.mdl
models/hunger/svenhands/w_hungershotgun.mdl
models/hunger/svenhands/w_m40a1.mdl
models/hunger/w_hunger357.mdl
models/keen/fernbig.mdl
models/keen/fernmed.mdl
models/keenhalloween/lightbush.mdl
models/keenhalloween/p_medkit.mdl
models/keenhalloween/pumpkin2.mdl
models/keenhalloween/pumpkinsnark.mdl
models/keenhalloween/skeleshark.mdl
models/keenhalloween/sticks.mdl
models/keenhalloween/v_medkit.mdl
models/keenhalloween/v_pumpkin.mdl
models/keenhalloween/w_pmedkit.mdl
models/kh6/evilnih.mdl
models/kh7/cyborg7.mdl
models/kh7/evilfreeman.mdl
models/kh7/motd_inf_d_S-Z.mdl
models/kh7/redshirt.mdl
models/kh7/skinnyguy.mdl
models/kh7/wootghost.mdl
models/opfor/p_knife.mdl
models/opfor/svenhands/v_knife.mdl
models/opfor/w_knife.mdl
models/oxyhalloween/v_bgrap_fixed.mdl
models/oxyhalloween/v_bgraptip.mdl
models/peany/picard.mdl
models/richard_boderman/plant.mdl
models/rngstuff/frozen1.mdl
models/sc_activist/houndeye.mdl
models/sc_activist/houndeyet.mdl
models/sc_activist/icky.mdl
models/sc_activist/ickyt.mdl
models/turr/p_keyboard.mdl
models/turr/v_keyboard.mdl
models/turr/w_keyboard.mdl
sound/aomlowercase/barnacle/bcl_alert2.wav
sound/aomlowercase/barnacle/bcl_bite3.wav
sound/aomlowercase/barnacle/bcl_die1.wav
sound/aomlowercase/barnacle/bcl_die3.wav
sound/aomlowercase/barnacle/bcl_tongue1.wav
sound/aomlowercase/bullchicken/bc_acid1.wav
sound/aomlowercase/bullchicken/bc_acid2.wav
sound/aomlowercase/bullchicken/bc_attack1.wav
sound/aomlowercase/bullchicken/bc_attack2.wav
sound/aomlowercase/bullchicken/bc_attack3.wav
sound/aomlowercase/bullchicken/bc_attackgrowl.wav
sound/aomlowercase/bullchicken/bc_attackgrowl2.wav
sound/aomlowercase/bullchicken/bc_attackgrowl3.wav
sound/aomlowercase/bullchicken/bc_bite1.wav
sound/aomlowercase/bullchicken/bc_bite2.wav
sound/aomlowercase/bullchicken/bc_bite3.wav
sound/aomlowercase/bullchicken/bc_die1.wav
sound/aomlowercase/bullchicken/bc_die2.wav
sound/aomlowercase/bullchicken/bc_die3.wav
sound/aomlowercase/bullchicken/bc_idle1.wav
sound/aomlowercase/bullchicken/bc_idle2.wav
sound/aomlowercase/bullchicken/bc_idle3.wav
sound/aomlowercase/bullchicken/bc_idle4.wav
sound/aomlowercase/bullchicken/bc_idle5.wav
sound/aomlowercase/bullchicken/bc_pain1.wav
sound/aomlowercase/bullchicken/bc_pain2.wav
sound/aomlowercase/bullchicken/bc_pain3.wav
sound/aomlowercase/bullchicken/bc_pain4.wav
sound/aomlowercase/bullchicken/bc_spithit1.wav
sound/aomlowercase/bullchicken/bc_spithit2.wav
sound/aomlowercase/bullchicken/bc_spithit3.wav
sound/aomlowercase/houndeye/he_alert1.wav
sound/aomlowercase/houndeye/he_alert2.wav
sound/aomlowercase/houndeye/he_alert3.wav
sound/aomlowercase/houndeye/he_attack1.wav
sound/aomlowercase/houndeye/he_attack2.wav
sound/aomlowercase/houndeye/he_attack3.wav
sound/aomlowercase/houndeye/he_blast1.wav
sound/aomlowercase/houndeye/he_blast2.wav
sound/aomlowercase/houndeye/he_blast3.wav
sound/aomlowercase/houndeye/he_die1.wav
sound/aomlowercase/houndeye/he_die2.wav
sound/aomlowercase/houndeye/he_die3.wav
sound/aomlowercase/houndeye/he_hunt1.wav
sound/aomlowercase/houndeye/he_hunt2.wav
sound/aomlowercase/houndeye/he_hunt3.wav
sound/aomlowercase/houndeye/he_hunt4.wav
sound/aomlowercase/houndeye/he_idle1.wav
sound/aomlowercase/houndeye/he_pain1.wav
sound/aomlowercase/houndeye/he_pain2.wav
sound/aomlowercase/houndeye/he_pain3.wav
sound/aomlowercase/houndeye/he_pain4.wav
sound/aomlowercase/houndeye/he_pain5.wav
sound/keen/locksmith.wav
sound/keenhalloween/dialogs/kh7/cryokeentxt.ogg
sound/keenhalloween/dialogs/kh7/freemanboss2.ogg
sound/keenhalloween/dialogs/kh7/hinttxt1.ogg
sound/keenhalloween/dialogs/kh7/hoardertxt.ogg
sound/keenhalloween/dialogs/kh7/mapendmm.ogg
sound/keenhalloween/dialogs/kh7/scitext.ogg
sound/keenhalloween/dialogs/kh7/woottext.ogg
sound/keenhalloween/hks1.wav
sound/keenhalloween/pl_gun3.wav
sound/keenhalloween/waterblast.wav
sound/keenhalloween/watercannonoff.wav
sound/keenhalloween/watercannonon.wav
sound/kh7/bonusbossmusic.ogg
sound/kh7/bossmusic.ogg
sound/kh7/wootghost.ogg
sound/tur/coin.wav
sound/tur/hongkong4.wav
sound/weapons/1911meu/MagIn.wav
sound/weapons/1911meu/MagOut.wav
sound/weapons/1911meu/SlidePull.wav
sound/weapons/1911meu/Sliderelease.wav
sprites/keenhalloween/picardcoin.spr